# EXAMPLE config file for snakemake workflows
# results will go in output/{exp-name}
out-dir: output
exp-name: tutorial

# expects paired end reads with format:
#    {reads-dir}/{sample_name}_1.fasta
#    {reads-dir}/{sample_name}_2.fasta
read_file_fmt: fasta
# replace with your reads directory
reads-dir: /fs/cbcb-lab/rob/students/jason/shared/SRR1265495/
# replace with your sample names to quantify (can be more than 1)
sample-names:
  - sample_01
  # - sample_02

# Path to reference transcriptome for salmon
txome-path: /fs/cbcb-lab/rob/students/jason/shared/annotations/hg19_clean.fa

# where to find folds, recommended to put this in {current working directory}/output/tutorial/folds
# for example my working directory is /fs/cbcb-lab/rob/students/skylar/perplexity
folds-dir: /fs/cbcb-lab/rob/students/skylar/perplexity/output/tutorial/folds

# Path to perplexity binary, and kfolds.sh script
perplexity-bin: target/release/perplexity
kfold-script: scripts/kfolds.sh

# Number of folds
k: 5

# VBEM weights to test with
# The default value is 1e-5
prior-weights:
  - 1e-6
  - 1e-5
  - 1e-4
  - 1e-3
  - 1e-2
  - 1e-1
  - 1e0
  - 1e1
  - 1e2
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7 
  - 8
  - 9
